# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Skypass CI

on:
  #push:
    #branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    #- run: npm run build --if-present
    #- run: npm test
      env: 
        CI: true
        DB_USERNAME: ${{secrets.DB_USERNAME}}
        DB_PASSWORD: ${{secrets.DB_PASSWORD}}
        DB_NAME: ${{secrets.DB_NAME}}
        DB_PORT: ${{secrets.DB_PORT}}
        DB_HOST: ${{secrets.DB_HOST}}
        PORT: ${{secrets.PORT}}
        NODE_ENV: ${{secrets.NODE_ENV}}
        SESSION_SECRET: ${{secrets.SESSION_SECRET}}
        JWT_SECRET: ${{secrets.JWT_SECRET}}
        JWT_EXPIRED: ${{secrets.JWT_EXPIRED}}
        REFRESH_TOKEN_EXPIRED: ${{secrets.REFRESH_TOKEN_EXPIRED}}
        MAIL_HOST: ${{secrets.MAIL_HOST}}
        MAIL_USER: ${{secrets.MAIL_USER}}
        MAIL_PASS: ${{secrets.MAIL_PASS}}
        IMAGEKIT_PUBLIC_KEY: ${{secrets.IMAGEKIT_PUBLIC_KEY}}
        IMAGEKIT_PRIVATE_KEY: ${{secrets.IMAGEKIT_PRIVATE_KEY}}
        IMAGEKIT_URL: ${{secrets.IMAGEKIT_URL}}
        MIDTRANS_SERVER_KEY: ${{secrets.MIDTRANS_SERVER_KEY}}
        MIDTRANS_CLIENT_KEY: ${{secrets.MIDTRANS_CLIENT_KEY}}
